<?php

use Illuminate\Database\Seeder;

class PaisTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $paises=[
            'Afeganistão',
            'África',
            'Albânia',
            'Alemanha',
            'Andorra',
            'Angola',
            'Antígua',
            'Arábia',
            'Argélia',
            'Argentina',
            'Armênia',
            'Austrália',
            'Áustria',
            'Azerbaidjão',
            'Bahamas',
            'Bangladesh',
            'Barbados',
            'Barein',
            'Belarus',
            'Bélgica',
            'Belize',
            'Benin',
            'Bolívia',
            'Bósnia',
            'Botsuana',
            'Brasil',
            'Brunei',
            'Bulgária',
            'Burkina',
            'Burundi',
            'Butão',
            'Cabo',
            'Camarões',
            'Camboja',
            'Canadá',
            'Catar',
            'Cazaquistão',
            'Chade',
            'Chile',
            'China',
            'Chipre',
            'Cingapura',
            'Colômbia',
            'Comores',
            'Congo',
            'Coréia do Norte',
            'Coréia do Sul',
            'Costa do Marfim',
            'Costa Rica',
            'Croácia',
            'Cuba',
            'Dinamarca',
            'Djibuti',
            'Dominica',
            'Egito',
            'El Salvador',
            'Emirados Árabes Unidos',
            'Equador',
            'Eritréia',
            'Eslováquia',
            'Eslovênia',
            'Espanha',
            'Estados Unidos',
            'Estônia',
            'Etiópia',
            'Fiji',
            'Filipinas',
            'Finlândia',
            'França',
            'Gabão',
            'Gâmbia',
            'Gana',
            'Geórgia',
            'Granada',
            'Grécia',
            'Guatemala',
            'Guiana',
            'Guiné',
            'Guiné-Bissau',
            'Guiné-Equatorial',
            'Haiti',
            'Holanda',
            'Honduras',
            'Hungria',
            'Iêmen',
            'Ilhas Marshall',
            'Ilhas Salomão',
            'Índia',
            'Indonésia',
            'Irã',
            'Iraque',
            'Irlanda',
            'Islândia',
            'Israel',
            'Itália',
            'Jamaica',
            'Japão',
            'Jordânia',
            'Kiribati',
            'Kuweit',
            'Laos',
            'Lesoto',
            'Letônia',
            'Líbano',
            'Libéria',
            'Líbia',
            'Liechtenstein',
            'Lituânia',
            'Luxemburgo',
            'Macedônia',
            'Madagáscar',
            'Malásia',
            'Malauí',
            'Maldivas',
            'Mali',
            'Malta',
            'Marrocos',
            'Maurício',
            'Mauritânia',
            'México',
            'Micronésia',
            'Moçambique',
            'Mianmar',
            'Moldávia',
            'Mônaco',
            'Mongólia',
            'Montenegro',
            'Namíbia',
            'Nauru',
            'Nepal',
            'Nicarágua',
            'Níger',
            'Nigéria',
            'Noruega',
            'Nova Zelândia',
            'Omã',
            'Palau',
            'Panamá',
            'Papua Nova Guiné',
            'Paquistão',
            'Paraguai',
            'Peru',
            'Polônia',
            'Portugal',
            'Quênia',
            'Quirguistão',
            'Reino Unido',
            'República Centro-Africana',
            'República Democrática do Congo',
            'República Dominicana',
            'Romênia',
            'Ruanda',
            'Russia',
            'San Marino',
            'Santa Lúcia',
            'São Cristóvão e Névis',
            'São Tomé e Príncipe',
            'São Vicente e Granadinas',
            'Senegal',
            'Serra Leoa',
            'Sérvia',
            'Seicheles',
            'Síria',
            'Somália',
            'Sri Lanka',
            'Suazilândia',
            'Sudão',
            'Suécia',
            'Suíça',
            'Suriname',
            'Tadjiquistão',
            'Tailândia',
            'Tanzânia',
            'Timor Leste',
            'Togo',
            'Tonga',
            'Trinidad e Tobago',
            'Tunísia',
            'Turquia',
            'Turcomenistão',
            'Tuvalu',
            'Ucrânia',
            'Uganda',
            'Uruguai',
            'Uzbequistão',
            'Vanuatu',
            'Venezuela',
            'Vietnã',
            'Zâmbia',
            'Zimbábue'];

        foreach ($paises as $pais){
            App\Pais::create([
                'nm_pais'=>$pais
            ]);
    }

    }
}
